# Generated by Django 5.1.4 on 2025-04-28 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_field_variety_tree_age_tree_nursery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='area',
            field=models.PositiveIntegerField(verbose_name='面積(㎡)'),
        ),
        migrations.AlterField(
            model_name='field',
            name='qr_suggestion',
            field=models.CharField(blank=True, max_length=20, verbose_name='畑QR提案'),
        ),
        migrations.AlterField(
            model_name='tree',
            name='nursery',
            field=models.CharField(blank=True, max_length=100, verbose_name='苗木業者'),
        ),
        migrations.CreateModel(
            name='TaskSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='作業名')),
                ('start_period', models.CharField(max_length=50, verbose_name='開始時期')),
                ('end_period', models.CharField(blank=True, max_length=50, verbose_name='終了時期')),
                ('unit', models.CharField(max_length=20, verbose_name='作業単位')),
                ('variety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.variety', verbose_name='品種')),
            ],
            options={
                'verbose_name': '作業スケジュール',
                'verbose_name_plural': '作業スケジュール一覧',
            },
        ),
    ]
