# Generated by Django 5.1.4 on 2025-04-28 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_field_area_alter_field_qr_suggestion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskschedule',
            options={'ordering': ['variety', 'seq'], 'verbose_name': '作業スケジュール', 'verbose_name_plural': '作業スケジュール一覧'},
        ),
        migrations.RemoveField(
            model_name='taskschedule',
            name='name',
        ),
        migrations.AddField(
            model_name='taskschedule',
            name='seq',
            field=models.PositiveIntegerField(default=1, verbose_name='番号'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskschedule',
            name='task_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.tasktype', verbose_name='作業種'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taskschedule',
            name='end_period',
            field=models.CharField(blank=True, max_length=20, verbose_name='終了時期'),
        ),
        migrations.AlterField(
            model_name='taskschedule',
            name='start_period',
            field=models.CharField(max_length=20, verbose_name='開始時期'),
        ),
        migrations.AlterField(
            model_name='taskschedule',
            name='unit',
            field=models.CharField(max_length=10, verbose_name='作業単位'),
        ),
        migrations.AlterField(
            model_name='taskschedule',
            name='variety',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.variety', verbose_name='品種'),
        ),
    ]
