# Generated by Django 5.1.4 on 2025-05-06 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_taskschedule_options_remove_taskschedule_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variety',
            name='fruit_type',
            field=models.CharField(choices=[('peach', '桃'), ('grape', 'ぶどう')], default='peach', max_length=10, verbose_name='果実種別'),
        ),
    ]
