# Generated by Django 5.1.4 on 2025-05-22 09:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_variety_fruit_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cluster_photos/')),
                ('taken_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='撮影日時')),
                ('note', models.TextField(blank=True, verbose_name='メモ')),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.cluster')),
            ],
        ),
    ]
